server {

  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /public-api {
    proxy_pass http://techaim.org:8080/public-api;
  }
}
