export enum currentNewsTypes {
    FETCH_CURRENT_NEWS_REQUEST = 'FETCH_CURRENT_NEWS_REQUEST',
    FETCH_CURRENT_NEWS_SUCCESS = 'FETCH_CURRENT_NEWS_SUCCESS',
    FETCH_CURRENT_NEWS_FAILURE = 'FETCH_CURRENT_NEWS_FAILURE',
  }
  