export enum formsTypes {
    FETCH_FORMS_REQUEST = 'FETCH_FORMS_REQUEST',
    FETCH_FORMS_SUCCESS = 'FETCH_FORMS_SUCCESS',
    FETCH_FORMS_FAILURE = 'FETCH_FORMS_FAILURE',
}

export enum formTypes{
    FETCH_FORM_REQUEST = 'FETCH_FORM_REQUEST',
    FETCH_FORM_SUCCESS = 'FETCH_FORM_SUCCESS',
    FETCH_FORM_FAILURE = 'FETCH_FORM_FAILURE',
  }