export enum partnersTypes {
  FETCH_PARTNERS_REQUEST = 'FETCH_PARTNERS_REQUEST',
  FETCH_PARTNERS_SUCCESS = 'FETCH_PARTNERS_SUCCESS',
  FETCH_PARTNERS_FAILURE = 'FETCH_PARTNERS_FAILURE',
}

export enum partnerTypes {
  FETCH_PARTNER_REQUEST = 'FETCH_PARTNER_REQUEST',
  FETCH_PARTNER_SUCCESS = 'FETCH_PARTNER_SUCCESS',
  FETCH_PARTNER_FAILURE = 'FETCH_PARTNER_FAILURE',
}
