export enum reportsTypes {
  FETCH_REPORTS_REQUEST = 'FETCH_REPORTS_REQUEST',
  FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS',
  FETCH_REPORTS_FAILURE = 'FETCH_REPORTS_FAILURE',
}

export enum reportTypes {
  FETCH_REPORT_REQUEST = 'FETCH_REPORT_REQUEST',
  FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS',
  FETCH_REPORT_FAILURE = 'FETCH_REPORT_FAILURE',
}