export enum supervisorsTypes {
    FETCH_SUPERVISORS_REQUEST = 'FETCH_SUPERVISORS_REQUEST',
    FETCH_SUPERVISORS_SUCCESS = 'FETCH_SUPERVISORS_SUCCESS',
    FETCH_SUPERVISORS_FAILURE = 'FETCH_SUPERVISORS_FAILURE',
    FETCH_SUPERVISOR_REQUEST = 'FETCH_SUPERVISOR_REQUEST',
    FETCH_SUPERVISOR_SUCCESS = 'FETCH_SUPERVISOR_SUCCESS',
    FETCH_SUPERVISOR_FAILURE = 'FETCH_SUPERVISOR_FAILURE',
  }
  