export enum team_membersTypes {
    FETCH_TEAM_MEMBERS_REQUEST = 'FETCH_TEAM_MEMBERS_REQUEST',
    FETCH_TEAM_MEMBERS_SUCCESS = 'FETCH_TEAM_MEMBERS_SUCCESS',
    FETCH_TEAM_MEMBERS_FAILURE = 'FETCH_TEAM_MEMBERS_FAILURE',
  }
  
  export enum team_memberTypes {
    FETCH_TEAM_MEMBER_REQUEST = 'FETCH_TEAM_MEMBER_REQUEST',
    FETCH_TEAM_MEMBER_SUCCESS = 'FETCH_TEAM_MEMBER_SUCCESS',
    FETCH_TEAM_MEMBER_FAILURE = 'FETCH_TEAM_MEMBER_FAILURE',
  }
  